travis:
  secure:
    BINSTAR_TOKEN: anffZU/klV9VeLC/79a0me1XZz/ZIY11X/DGlznh7Z6yVNdXldMATP740FEWnpnPk6z0nAOzSKGAQRIPV7OKL49hfx9MGNtqwmM5tGMjnda8SF2Idd/vdW0AO8MRi3XsJ0ajFyNOpoMQGD4aXiTJrIcpTdGiQKnm7b5cc3dglVf09CDBnP3GKLMWwG2OqVLEYSrndRxvSawoQRg2GKFsvtW1OKY7Uwe6ITV/FdgRK+MJg5j5M9fdn+KSu1gjPZIkzmBov/2dHDLJc7ATBRSlDuIvDZB6OBHfzs1qSLIhZ35jYjrkhE5mEU6fKhaXH+HjKc/oQbTvliJa9fvNjO4ueOteR6LMiyJEQ2K9/jy1qBdnc3qDHGSvlfeCzkCxTPjflObS96Yt+xOt4xVWBJrqFXDbOkRgWI/1ayx0mr4/+RDDgIQU7TlP5aB9iB2iOwUSMsJ+tPi3iyCcRk+39T5IFuEy4HGUjav+G7yn+suWP0i7ZWjSqLFJ2nI+zxb+wjH/IFx7rmd4IDeu1HxXjd3CQR6Qj0V4ZSPGV8fS2hWfwqIMEO/9fKAhvsvhViK9+hA6m+l3HooQ4SPNDYVPuNPdx692ByqnyFV4o11Hthae1j7Zkb1tDfxt1BYIXIZHxv5MGC72u+dftd93ulyQaox0yuSElwHosYpwxAm3BL/a5yk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
