travis:
  secure:
    BINSTAR_TOKEN: ELc9+f2ltFxRoo0mkOcPJDd2D8gmqKMo2+VO/IhNUVKMIgfHGtYntajEcTmQuP5H2XSI7rAhAuhULJtt1V9evgce1dlRziglvJo7LuD+dgPCaMvXQVerv6U9h9Fjlh9OMog8ykDi30MFzG1q3yM/VQCGWa7YDcuJlrjHqVkVzE7sz6/v5iUD4jaxzOGdinAHA2WgN23uVnJveRaskHGIWlv/Ps/di4+jaXABIuHWfWGOHWIN9v+OfGGbirA3L2PwhOVH+pluh6uAJ9ZIiP5xNGOnf5SwqXzL23mELzDouFlFAbWM5zZ66JHkDCYrP4hezwVPXb4imFEKRj8A4OGZongnPJKKidaOeTkDBKApSBcbVjuyENYJ+Nv5WeJGohhjHDU7PR3Zy9+bpFytVery+mPPWrzRfbNRCGUE8hoIITTrR4iRIoAzRlb2LbmID0vttPDG6150Le+DlM9W8YJ00enbKjjeKeXKsdDVUicas0/AI9N5XRVb/9ZUREgSlZc3C/t4a2Ip5kQD9wdym8IxY7OOnDy173/Jq2VKfpSbDdjw9OSnfC/TJiUm9fju8zBw5AfO1s739wi2mNx87z9j6OHy+oKAAvcd6v6xOPOENG+RXWVWK5frLXm3b3ymkV40KayAUngnBRPYC0E6JhRFA442fewgfg2L+88sLl3k2Mg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
